//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverId { get; set; }
        public Nullable<int> TruckId { get; set; }
        public string DriverName { get; set; }
        public string DriverSurname { get; set; }
        public Nullable<System.DateTime> DriverDateOfBirth { get; set; }
        public string DriverDrivingLicense { get; set; }
    
        public virtual Truck Truck { get; set; }
    }
}
