//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Truck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truck()
        {
            this.Orders = new HashSet<Order>();
            this.Drivers = new HashSet<Driver>();
        }
    
        public int TruckId { get; set; }
        public string TruckName { get; set; }
        public string TruckModel { get; set; }
        public string TruckType { get; set; }
        public Nullable<int> TruckWeightLimit { get; set; }
        public Nullable<int> TruckMaxSize { get; set; }
        public Nullable<bool> TruckCondition { get; set; }
        public Nullable<System.DateTime> TruckYearOfIssue { get; set; }
        public Nullable<bool> TruckState { get; set; }
        public string TruckLicState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
    }
}
